name: Build and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Package
      run: mvn clean install

    - name: Publish to GitHub Packages
      run: |
        mvn deploy -Dregistry=https://maven.pkg.github.com/pravesh-77/GitHub-Packages-Maven -DrepositoryId=github -Dtoken=${{ secrets.GH_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
